swagger: "2.0"
info:
  description: "Healtcare system Billing APIs."
  version: "1.0.0"
  title: "Health care system - billing"
  contact:
    email: "cs62@njit.edu"
tags:
- name: "procedures"
  description: "Everything about procedures and rates"
- name: "claims"
  description: "Billing claims"
schemes:
- "https"
- "http"
paths:
  /procedures:
    get:
      tags:
      - "procedures"
      summary: "List of all the procedures available in the system"
      description: "Returns the List all the procedures codes and information (CPT, HCPCS codes) paired with diagnosis (ICD codes)"
      operationId: "procedures"
      responses:
        "405":
          description: "Invalid input"
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Procedure"
  /procedures/{procedureId}/rates:
    get:
      tags:
      - "procedures"
      summary: "Rate of a procedure"
      description: "Returns the rate of a procedure with id {procedureId}."
      operationId: "procedureRate"
      parameters:
      - name: "procedureId"
        in: "path"
        description: "Procedure Id"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ProcedureRate"
        "400":
          description: "Invalid status value"
  /claims:
    get:
      tags:
      - "claims"
      summary: "Returns list of all claims"
      description: "Returns list of all claims"
      operationId: "getClaims"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Claim"
        "400":
          description: "Invalid tag value"
  /claims/{claimId}:
    get:
      tags:
      - "claims"
      summary: "Find claim by ID"
      description: "Returns a single claim"
      operationId: "getClaimById"
      parameters:
      - name: "claimId"
        in: "path"
        description: "ID of claim that needs to be updated"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Claim"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
    post:
      tags:
      - "claims"
      summary: "Creates a claim"
      description: ""
      operationId: "createClaim"
      parameters:
      - name: "claimId"
        in: "path"
        description: "ID of claim that needs to be updated"
        required: true
        type: "string"
      responses:
        "405":
          description: "Invalid input"
    put:
      tags:
      - "claims"
      summary: "Updates a claim"
      description: ""
      operationId: "updateClaim"
      parameters:
      - name: "claimId"
        in: "path"
        description: "ID of pet that needs to be updated"
        required: true
        type: "string"
      responses:
        "405":
          description: "Invalid input"
    delete:
      tags:
      - "claims"
      summary: "Deletes a claim"
      description: ""
      operationId: "deletePet"
      parameters:
      - name: "claimId"
        in: "path"
        description: "ID of pet that needs to be updated"
        required: true
        type: "string"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
definitions:
  ProcedureRate:
    type: object
    properties:
      id:
        type: "string"
        description: "rate id"
      procedureId:
        type: string
        description: "Id of the procedure"
      rate:
        type: integer
  Diagnosis:
    type: "object"
    properties:
      id:
        type: "string"
        description: "diagnosis id"
      code:
        type: "string"
        description: "codes for the diagnosis"
      description:
        type: "string"
        description: "description for the diagnosis"
  Procedure:
    type: "object"
    properties:
      id:
        type: "string"
        description: "procedure id"
      codingType:
        type: "string"
        enum:
        - "CPT"
        - "HCPCS"
      diagnosisCode:
        $ref: "#/definitions/Diagnosis"
      code:
        type: "string"
        description: "codes for the procedure"
      description:
        type: "string"
        description: "description for the procedure"
  Claim:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "string"
        description: "claim id"
      patientId:
        type: "string"
        description: "patient id"
      insuranceId:
        type: "string"
        description: "insurance detail id"
      procedures:
        type: "array"
        description: "list of procedures taken"
        items:
          $ref: "#/definitions/Procedure"
      dateCreated:
        type: "string"
        description: "ISO format date created"
      dateUpdated:
        type: "string"
        description: "ISO format date updated"
      status:
        type: "string"
        description: "status of the claim"
        enum:
        - "initiated"
        - "accepted"
        - "rejected"
        - "denied"
        - "sent_for_adjudication"
        - "deleted"